
# A string used as a project reference and for naming generated client libraries
# Do not change this once you've deployed.
project_id = "wscoyigjjcevriqqyxwo"

[api]
enabled = true
# Port to use when running `npx supabase start`
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
# Max rows to return when selecting from the database
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_expiry = 43200

[realtime]
enabled = true

[storage]
enabled = true
file_size_limit = "50MiB"

[edge_functions]
enabled = true

[analytics]
enabled = false
port = 54327

# Add new function with service role access
[functions.get-user-by-email]
verify_jwt = true
