// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wscoyigjjcevriqqyxwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzY295aWdqamNldnJpcXF5eHdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NTkxMjEsImV4cCI6MjA1OTUzNTEyMX0.mD8wIMJX8jdKHxhFJMcRsnDPIiZojamvAGrGC-S9RRs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);